config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resources :comments
  end

  

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :text, presence: true

  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @article = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render action: :new 
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: :edit 
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)    
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  def comment_params
    params.require(:comment).permit(:author, :body)    
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: :new #plain: 'new'
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:email, :message)    
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
    
  end

  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/create.html.erb
<h2>Thanks!</h2>
<p>Article is created</p>

<%= link_to 'Show all articles', articles_path %>

app/views/articles/edit.html.erb
<h2>Edit article</h2>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>
	<p>	
		<%= f.label :text %><br/>
		<%= f.text_area :text %>
	</p>
	<p><%= f.submit %></p>
<% end %>

app/views/articles/index.html.erb
<h2>List of articles</h2>

<% @article.each do |article_item| %>
	<div style="border: 1px solid; margin: 10px; padding: 20px;">
		<h3><%= article_item.title %></h3>
		<p style="padding-left: 20px;"><%= article_item.text %></p>
		<%= link_to 'Show article', article_path(article_item) %>
		<%= link_to 'Edit article',  edit_article_path(article_item) %>
		<%= link_to 'Delete article', article_path(article_item), method: :delete, data: {confirm: "Are you sure?"}, class: "delete-button" %>
	</div>
<% end %>

app/views/articles/new.html.erb
<h2>New article</h2>

<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title %>
	</p>
	<p>	
		<%= f.label :text %><br/>
		<%= f.text_area :text %>
	</p>
	<p><%= f.submit %></p>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p><%= @article.text %></p>

<hr/>
<%  @article.comments.each do |item| %>
<p><b>Author: <%= item.author %></b><br/>
Comment: <i><%= item.body %></i></p>
<hr/>
<%end%>

<h3>Comments</h3>
<%= form_for([@article, @article.comments.build]) do |f| %>
	<p>
		<%= f.label :author %><br/>
		<%= f.text_field :author %>
	</p>
	<p>	
		<%= f.label :body %><br/>
		<%= f.text_area :body %>
	</p>
	<p><%= f.submit %></p>
<% end %>

app/views/contacts/create.html.erb
<h2>Thanks!</h2>

app/views/contacts/new.html.erb
<h2>Contact us</h2>

<%= form_for :contact, url: contacts_path do |f| %>
	<% if @contact && @contact.errors.any? %>
		<ul class="errors">
			<% @contact.errors.full_messages.each do |item| %>
			<li><%= item %></li>
			<% end %>
		</ul>
	<% end %>
	<p>
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</p>
	<p>	
		<%= f.label :message %><br/>
		<%= f.text_area :message %>
	</p>
	<p><%= f.submit 'Send message'%></p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>Logo</div>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h2>About us</h2>

app/views/pages/terms.html.erb
<h2>Terms</h2>